version: "3.9"

services:
  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tododb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: todo-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  todo-db-data:
